[en]
  contentDir = 'content/en'
  languageCode = 'en'
  languageName = 'English'
  weight = 1

[zh-Hans]
  contentDir = 'content/zh-Hans'
  hasCJKLanguage = true
  languageCode = 'zh-Hans'
  languageName = '简体中文'
  weight = 2
